Vagrant.configure("2") do |config|

	#Utilise une box Ubuntu standard
	config.vm.box = "ubuntu/bionic64"

	#Nom de la VM
	config.vm.hostname = "vm-test"

	#Config réseau: IP privée
	config.vm.network "private_network", ip: "192.168.56.10"

	#Configuration VirtualBox
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "1024"
		vb.cpus = 1
	end
end
