name: Deploy to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : récupérer le code du dépôt
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : configurer la clé SSH pour accéder au serveur
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SRVTEST_IP }} >> ~/.ssh/known_hosts

    # Étape 3 : tester la connexion SSH
    - name: Test SSH connection
      run: ssh -i ~/.ssh/id_ed25519 ${{ secrets.SRVTEST_USER }}@${{ secrets.SRVTEST_IP }} "ls -la"

    # Étape 4 : déployer l'application avec HTTPS + token
    - name: Deploy application
      env:
        GITHUB_TOKEN_DEPLOY: ${{ secrets.TOKEN_DEPLOY }}
        SSH_USER: ${{ secrets.SRVTEST_USER }}
        SSH_HOST: ${{ secrets.SRVTEST_IP }}
      run: |
        ssh -i ~/.ssh/id_ed25519 $SSH_USER@$SSH_HOST bash -s <<'ENDSSH'
          set -e
          DIR="/home/$SSH_USER/Projet_Test"

          # Créer le dossier si inexistant
          mkdir -p "$DIR"

          # Cloner le dépôt si il n'existe pas, sinon pull
          if [ ! -d "$DIR/.git" ]; then
            git clone https://$GITHUB_TOKEN_DEPLOY@github.com/m-andrianjarasoa/Projet_Test.git "$DIR"
          else
            cd "$DIR"
            git pull origin main
          fi

          echo "Déploiement terminé"
        ENDSSH


