name: Deploy to Hetzner

# Déclencheur : à chaque push sur la branche main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : récupérer le code du dépôt
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : configurer la clé SSH
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" | tr -d '\r' > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SRVTEST_IP }} >> ~/.ssh/known_hosts

    # Étape 3 : tester la connexion SSH
    - name: Test SSH connection
      run: ssh -vvv -i ~/.ssh/id_ed25519 ${{ secrets.SRVTEST_USER }}@${{ secrets.SRVTEST_IP }} "ls -la"


    # Étape 4 : déployer l'application
    - name: Deploy application
      run: |
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.SRVTEST_USER }}@${{ secrets.SRVTEST_IP }} "
          mkdir -p /home/${{ secrets.SRVTEST_USER }}/Projet_Test &&
          cd /home/${{ secrets.SRVTEST_USER }}/Projet_Test &&
          if [ ! -d "/home/nantenaina/Projet_Test/.git" ]; then
            git clone git@github.com:TonUtilisateur/TonDepot.git /home/nantenaina/Projet_Test
          else
            cd /home/nantenaina/Projet_Test
            git pull origin main
          fi
